apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: gcr.io/r2d4minikube/notebook
    sync:
      'hack/*.py': "/home/jovyan/work/lib/"
deploy:
  kubectl:
    manifests:
    - k8s/notebook.yaml
