apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: gcr.io/mrick-gcp/notebook
    sync:
      "fairing-py/**": "/home/jovyan/work/lib/"
      "config/ipython_kernel_config.py": "/home/jovyan/.ipython/profile_default/ipython_kernel_config.py"
deploy:
  kubectl:
    manifests:
    - k8s/notebook.yaml
